export const COURSE = [
  {
    id: 1,
    title: 'Intro to JavaScript',
    author: 'John Doe',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
  {
    id: 2,
    title: 'Intro to TypeScript',
    author: 'Blake Samuel',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
  {
    id: 3,
    title: 'Foundation of OOP',
    author: 'Mike Henry',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
  {
    id: 4,
    title: 'Functional Programming',
    author: 'Janeth Sasha',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
  {
    id: 5,
    title: 'How to unit test',
    author: 'Amaka Joy',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
  {
    id: 6,
    title: 'Responsive Web Design',
    author: 'Emmanuel Terry',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
  {
    id: 7,
    title: 'Intro to Laravel',
    author: 'Sam Eddie',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
  {
    id: 8,
    title: 'How to React',
    author: 'Jane Sammie',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
  {
    id: 9,
    title: 'Intro to CSS',
    author: 'Jack Tony',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
  {
    id: 10,
    title: 'Intro to NodeJs',
    author: 'Larry Simpson',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
  {
    id: 11,
    title: 'Creating UI with Figma',
    author: 'Matilda Jennie',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
  {
    id: 12,
    title: 'Component Design made easy',
    author: 'Ivie Maryann',
    lesson: '15 lesson',
    hour: '40 Hours',
  },
] as const;
